[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -ra
    --strict-markers
    --strict-config
    --cov=app
    --cov-report=term-missing
markers =
    routes: pruebas de endpoints Flask
    database: pruebas que interactuan con la base de datos SQLite
